[archer2] Add initial configuration
ukri-excalibur/excalibur-tests pull request #45
Opened 2022-10-12 19:13 UTC by giordano

This should be working, but I'm having lots of troubles with submitting the jobs.  I believe this is at least in part related to the fact ARCHER2 compute nodes can't access the home directory, but it isn't clear to me _what_ is trying to access the home directory, I'll need to investigate more.

Fix #43

2022-10-12 22:00 UTC, giordano commented
This is part of the issue, but there is more to it: https://github.com/spack/spack/issues/33265.

2022-10-13 10:06 UTC, giordano commented
With the last two commit, to work around the issues I mentioned above, I was able to successfully run the example benchmark on archer2:
```
[==========] Running 1 check(s)
[==========] Started on Thu Oct 13 10:55:33 2022

[----------] start processing checks
[ RUN      ] SombreroBenchmark /cc391b86 @archer2:compute-node+default
[       OK ] (1/1) SombreroBenchmark /cc391b86 @archer2:compute-node+default
P: flops: 1.16 Gflops/seconds (r:1, l:None, u:None)
[----------] all spawned checks have finished

[  PASSED  ] Ran 1/1 test case(s) from 1 check(s) (0 failure(s), 0 skipped)
[==========] Finished on Thu Oct 13 10:58:03 2022

============================================================================================================================================================================================================================================
PERFORMANCE REPORT
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
[SombreroBenchmark /cc391b86 @archer2:compute-node:default]
  num_tasks: 1
  num_gpus_per_node: 0
  num_tasks_per_node: 1
  num_cpus_per_task: 1
  performance:
    - flops: 1.16 Gflops/seconds (r: 1 Gflops/seconds l: -inf% u: +inf%)
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
```

2022-10-13 10:26 UTC, aturner-epcc requested changes
Just a few notes on the compiler environments available and additional options to support Fortran + MPI compilation with GCC versions >= 10

2022-10-13 10:26 UTC, aturner-epcc commented on spack-environments/archer2/compute-node/spack.yaml
> +      extra_rpaths: []
I do not see this compiler installed on ARCHER2?

2022-10-13 10:26 UTC, aturner-epcc commented on spack-environments/archer2/compute-node/spack.yaml
> +  - compiler:
Not available on ARCHER2

2022-10-13 10:26 UTC, aturner-epcc commented on spack-environments/archer2/compute-node/spack.yaml
> +      extra_rpaths: []
Not available on ARCHER2

2022-10-13 10:26 UTC, aturner-epcc commented on spack-environments/archer2/compute-node/spack.yaml
> +      extra_rpaths: []
This compiler should not be included - GCC 8 is only installed to support CCE, it does not work as a standalone compiler environment

2022-10-13 10:26 UTC, aturner-epcc commented on spack-environments/archer2/compute-node/spack.yaml
> +      extra_rpaths: []
For GCC >=10, you will probably need to add:

```
fflags: -fallow-argument-mismatch
```

To allow MPI code to compile

2022-10-13 10:26 UTC, aturner-epcc commented on spack-environments/archer2/compute-node/spack.yaml
> +      extra_rpaths: []
These compilers are not available on ARCHER2

2022-10-13 10:50 UTC, giordano commented
Interesting, I've got all compilers with `spack compiler find` on a login node.  Anyway, I removed the extra compilers and set `fflags` for GCC >= 10.

2022-10-13 12:45 UTC, tkoskela approved these changes
Tried this on archer2 and got the example running successfully. Came up with a couple of improvements but those can be done in separate PRs. Opened issues #46 and #47.

2022-10-13 13:47 UTC, merged